### ISSUE TITLE
Fix compilation on MinGW

### ISSUE THREAD

**Issue by 21347** [atomicobject/heatshrink#7]
Hi there,

great bunch of code!

However, when I was testing it, I was stuck to MinGW; but there's nor "err.h".

Workaround: replace
```c
#include <err.h>
```
by
```c
#if !defined(__MINGW32__)
#include <err.h>
#else

#define err(retval, ...) do { \
    fprintf(stderr, __VA_ARGS__); \
    fprintf(stderr, "Undefined error: %d\n", errno); \
    exit(retval); \
} while(0)

#endif
```
in heatshrink.c. After that, it compiles and runs flawlessly.

**Comment by silentbicycle** [comment]
This should now be resolved, via #10 and #12 .
